"""State definitions for the agentic RAG workflow."""

from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class ConversationMessage:
    """Represent a previous conversation message."""

    role: str
    content: str


@dataclass(slots=True)
class CodeArtifact:
    """Represent the current source-code artifact in a conversation."""

    filename: str
    language: str
    source_code: str


@dataclass(slots=True)
class AgentState:
    """Shared state passed between nodes of the agentic RAG workflow."""

    query: str
    user_id: str

    document_id: str | None = None

    route: str = "general"
    tool_result: str | None = None

    conversation_history: list[ConversationMessage] = field(
        default_factory=list,
    )

    # Current code being discussed or modified in the conversation.
    code_artifact: CodeArtifact | None = None

    # New code artifact generated by the current agent request.
    generated_code_artifact: CodeArtifact | None = None

    retrieved_chunks: list[dict[str, Any]] = field(default_factory=list)

    answer: str | None = None

    openai_answer: str | None = None

    gemini_answer: str | None = None

    verification_passed: bool = False

    verification_reason: str | None = None

    retrieval_attempts: int = 0

    error: str | None = None
