"""create users table

Revision ID: f80df87bba8c
Revises: 7848a68b2b61
Create Date: 2026-08-12 18:10:43.695578

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f80df87bba8c"
down_revision: str | Sequence[str] | None = "7848a68b2b61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
